Basic operators, maths
javascript-tutorial/bn.javascript.info pull request #113
Opened 2021-01-16 07:59 UTC by MShafquat

Translated all the files in there.

2021-01-16 07:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/bn.javascript.info?pullRequest=113) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/bn.javascript.info?pullRequest=113) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/bn.javascript.info?pullRequest=113) it.</sub>

2021-01-18 02:56 UTC, msisaifu requested changes
কয়েকটি লাইনে চেঞ্জ করলে, একেবারেই পারফেক্ট বলা যায় (y). @jamal-pb95 or @raikusy এটিকে approve করতে পারেন।

2021-01-18 02:56 UTC, msisaifu commented on 1-js/02-first-steps/08-operators/article.md
> +- ঘাত `**`.
Exponentiation এর বাংলা সূচক বেশী মানানসই মনে হয়

2021-01-18 02:56 UTC, msisaifu commented on 1-js/02-first-steps/08-operators/article.md
> +alert( 8 ** (1/3) ); // ২ (কোনো সংখ্যার সূচক ১/৩ আর সংখ্যাটির ঘনমূল এক)
২ (কোনো সংখ্যার সূচক ১/২ আর সংখ্যাটির বর্গমূল একই)
২ (কোনো সংখ্যার সূচক ১/৩ আর সংখ্যাটির ঘনমূল একই)

2021-01-18 02:56 UTC, msisaifu commented on 1-js/02-first-steps/08-operators/article.md
> +alert( +x ); // ২
alert( +x ); // ১

2021-01-18 02:56 UTC, msisaifu commented on 1-js/02-first-steps/08-operators/article.md
> +// সংখ্যায় রূপান্তর করে
সংখ্যায় রূপান্তর করা

2021-01-18 02:56 UTC, msisaifu commented on 1-js/02-first-steps/08-operators/article.md
> +একজন ম্যাথমেটিশিয়ানের দিক থেকে চিন্তা করলে, অযথা প্লাসের ব্যবহার অদ্ভুত লাগতে পারে। কিন্তু একজন প্রোগ্রামারের কাছে এটা তেমন কিছুই না: ইউনারি প্লাস আগে কাজ করে স্ট্রিংকে সংখ্যায় রূপান্তর করে, তারপর বা
ম্যাথমেটিশিয়ানের পরিবর্তে গণিতবিদ লিখা যায়

2021-01-18 02:56 UTC, msisaifu commented on 1-js/02-first-steps/08-operators/article.md
> +স্কুলে আমরা শিখেছি `1 + 2 * 2` এক্সপ্রেশনের গুণ যোগের আগে করতে হবে। এই জিনিসটাই হচ্ছে প্রিসিডেন্স। গুণের প্রিসিডেন্স যোগের চেয়ে *বেশি*।
স্কুলে আমরা শিখেছি `1 + 2 * 2` এক্সপ্রেশনের গুণের কাজ যোগের আগে করতে হয়।

2021-01-18 02:56 UTC, msisaifu commented on 1-js/02-first-steps/08-operators/article.md
> +জাভাস্ক্রিপ্টে অনেক অপারেটর আছে। প্রত্যেক অপারেটরের একটি প্রিসিডেন্স নাম্বার আছে। যাদের নাম্বার বেশি তারা এক্সিকিউট হবে। প্রিসিডেন্স এক হলে বাম থেকে ডানে এক্সিকিউট হবে।
যাদের নাম্বার বেশি তারা আগে এক্সিকিউট হবে।

2021-01-18 02:56 UTC, msisaifu commented on 1-js/02-first-steps/08-operators/article.md
> +এটা [প্রিসিডেন্স টেবিলের](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence) একটা অংশ (আপনার এটা মনে রাখতে হবে না, শুধু লক্ষ্য করুন ইউনারি অপারেটরদের প্র
(আপনার এটা মনে রাখতে হবে না, শুধু লক্ষ্য করুন ইউনারি অপারেটরদের প্রিসিডেন্স তাদের সংশ্লিষ্ট বাইনারি অপারেটরের চেয়ে বেশি)

2021-01-18 02:56 UTC, msisaifu commented on 1-js/02-first-steps/08-operators/article.md
> +মজার কোড, তাই না? আমাদের এটা কীভাবে কাজ করে তা বুঝা উচিৎ, কারণ আমরা প্রায়ই এটা জাভাস্ক্রিপ্ট লাইব্রেরিগুলোতে দেখতে পাবো।
কারণ আমরা অনেক সময় এটা জাভাস্ক্রিপ্ট লাইব্রেরিগুলোতে দেখতে পাবো

2021-01-18 02:56 UTC, msisaifu commented on 1-js/02-first-steps/08-operators/1-increment-order/task.md
> +নিচের কোডের পর `a`, `b`, `c` ও `d` এর ফাইনাল ভ্যালু কী হবে?
নিচের কোডের `a`, `b`, `c` ও `d` এর ফাইনাল ভ্যালু কী হবে?

2021-01-18 02:56 UTC, msisaifu commented on 1-js/02-first-steps/08-operators/2-assignment-result/task.md
> +নিচের কোডের পর `a` আর `x` এর মান কী হবে?
নিচের কোডে `a` এবং `x` এর মান কী হবে?

2021-01-18 13:00 UTC, MShafquat commented on 1-js/02-first-steps/08-operators/article.md
> +## টার্ম: "ইউনারি", "বাইনারি", "অপারেন্ড"
টার্মের সাথে সমূহ মানাচ্ছে না। "টার্মস" করে দিলাম। :blush:

2021-01-18 13:03 UTC, MShafquat commented
@msisaifu আপনার রিভিউয়ের জন্য অসংখ্য ধন্যবাদ। যেভাবে বললেন সেভাবেই চেঞ্জ করলাম।
/done

2021-06-21 07:33 UTC, jaamaal95 approved these changes
well done @MShafquat

2021-06-21 07:33 UTC, merged